/**
 * Jeju DWS Training Module
 *
 * Re-exports from the consolidated @jejunetwork/training package.
 *
 * @deprecated Import directly from @jejunetwork/training instead
 */

// Re-export everything from the training package
export {
  type AgentTrajectory,
  type APIServerConfig,
  type AtroposEnvConfig,
  type AtroposMessage,
  type AtroposState,
  AutocratTrainingClient,
  type BatchData,
  type Board,
  type BridgeConfig,
  type BridgedRunState,
  type Cell,
  type CheckpointData,
  type ClientInfo,
  type ClientRegistration,
  type Completion,
  type CompletionResult,
  type CoordinatorConfig,
  type CoordinatorProgress,
  type CoordinatorState,
  CrossChainTrainingBridge,
  CrucibleTrainingClient,
  type CrucibleTrainingMetrics,
  // GRPO
  createAtroposServer,
  createAutocratTrainingClient,
  createCrossChainBridge,
  // Integrations
  createCrucibleTrainingClient,
  createDistributedGRPOTrainer,
  // Compute
  createDWSClient,
  createFundamentalPredictionEnv,
  createGRPOTrainer,
  // Psyche
  createPsycheClient,
  // Environments
  createTicTacToeEnv,
  DistributedGRPOTrainer,
  type DWSClientConfig,
  type DWSJobStatus,
  DWSTrainingClient,
  type FundamentalEnvConfig,
  type FundamentalMessage,
  FundamentalPredictionEnv,
  type GameState,
  type GameStep,
  type GameTrajectory,
  GRPOTrainer,
  getDefaultDWSConfig,
  isDWSAvailable,
  type JudgeResult,
  type Model,
  type ModelDeploymentProposal,
  type Move,
  type Player,
  PsycheClient,
  type PsycheConfig,
  type PsycheTrainingMetrics,
  type RegisterEnv,
  type Registration,
  type RewardDistribution,
  type RolloutData,
  type RunMetadata,
  type ScoredData,
  type ScoredDataGroup,
  startAtroposServer,
  TicTacToeEnv,
  type TrainerStatus,
  type TrainingAgentConfig,
  type TrainingConfig,
  type TrainingEnvironment,
  type TrainingItem,
  type TrainingJobRequest,
  type TrainingJobResult,
  type TrainingJobStatus,
  type TrainingMetrics,
  type TrainingProposal,
  type TrainingRun,
  type TrajectoryStep,
  trajectoryToTrainingFormat,
  type WitnessProof,
} from '@jejunetwork/training'
